spring.application.name=synaris

spring.datasource.url=jdbc:mysql://localhost:2006/synaris
spring.datasource.username=root
spring.datasource.password=Xperiasp575@

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true


logging.level.org.flywaydb=DEBUG